### ISSUE TITLE
Code rewrite

### ISSUE THREAD

**Issue by MikeDev101** [the-yoom-project/Yoom#4]
Hello everyone. I'm currently in the process of rewriting Yoom to use my CloudLink API. Not only that CloudLink will be faster and more versatile than using a fixed-IP cloud variable server, but I can easily manage and modify server software whenever it is called for. The yoom.sb3 and index.html are currently out of date, please don't report bugs on those at this time. I'll close this thread when I finish rewriting the code and finalized the server code.

**Comment by DabDatBass** [comment]
You can also host Yoom with old.js

**Comment by VelocityDesign** [comment]
Ok :)

**Comment by VelocityDesign** [comment]
If possible, I would make Yoom rely on an open server that would allow for alternative clients (E.G. a Android, iPhone, or UWP app.

**Comment by MikeDev101** [comment]
> If possible, I would make Yoom rely on an open server that would allow for alternative clients (E.G. a Android, iPhone, or UWP app.

Sure, I don't mind. Though the plan is to have it linked with the public test server and accessible VIA using CLNS/CNLS (CloudLine stuff...)

**Comment by VelocityDesign** [comment]
Ok. I would be able to code a version for electron (Which, in turn, provides a macOS, Snap (Linux), and UWP).

**Comment by MikeDev101** [comment]
> Ok. I would be able to code a version for electron (Which, in turn, provides a macOS, Snap (Linux), and UWP).

Wowza, that sounds great! I plan on just making it as an HTML file that can be viewed in any standard browser or through nw.js.
