### ISSUE TITLE
Just A Few Questions (EZ-Games) 

### ISSUE THREAD

**Issue by EZRockEatsWaffles** [the-yoom-project/Yoom#5]
Sorry if this is the wrong place to be contacting you about _Yoom!_, I just had a few questions for you (as well as some information). 

As I said on your Scratch profile, I'm still interested in being a moderator, although, life has gotten busier since school has started back up, and just life, in general, has me occupied, so I'm not sure if I can commit to certain times - is this fine? I'll do my best to moderate when possible, but I also want to balance out my screen time and my time doing other things more productive.  

Second question, will you make an easy to understand guide in the future on how to download and run _Yoom!_? I'm extremely unintelligent on the technical side of things, so I'm wondering if the process of downloading and running the program will be easy. 

That's all I have for now. I may have more questions for you in the future. I also want to clarify that I'll be letting my parents know about this, and see if they'll okay with me doing this - just wanna make sure I'm clear with them on this so that I can eliminate the fear of them forcing me to quit. 

Thanks man, and best of luck on this! I'm excited about the future of this project. :)

**Comment by MikeDev101** [comment]
Hey there, thanks for showing interest in Yoom. 

As for the schedule situation, It's perfectly fine. When we're online, at least once a week of activity on Yoom is fair. 

I will provide help on how to use Yoom. Though, most of the technical work will be handled by yours truly. All you would need to do is open the Yoom client and log in.

Also, as for the moderation side of things, the client and the server will have a built-in word blocking system (kinda like a whitelist). However, human moderation will be needed. Most of the moderation will be handled automatically, and if in case there is a need for human intervention, that's what the role of the moderator is for.
