### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by MikeDev101** [the-yoom-project/Yoom#6]
Regarding recent events from the Meower project, I officially announce that Yoom will serve as a spinoff project for Meower. Once development on Meower is finalized, we will begin development on Yoom.

Fundamentally, all that we need to do is the following:

1. Extract Meower source code.
2. Replace cloud variable code with CloudLink.
3. ???
4. Profit.

**Comment by VelocityDesign** [comment]
Hmm... What if Yoom! was independent of scratch and distributed by turbowarp or something? That would be nice so we could add chat and stuff.

**Comment by MikeDev101** [comment]
> Hmm... What if Yoom! was independent of scratch and distributed by turbowarp or something? That would be nice so we could add chat and stuff.

Always has been.
